Add Gpio abstraction to adc library
uw-midsun/firmware_xiv pull request #163
Opened 2020-09-15 12:43 UTC by mitchellostler

Alright, back at it with another try. This time, the adcChannel defs are the all the same, and I built on top of the library with Gpio Defs. Will check results of PR check but should be all good. 

Overview of changes:
Adc.h
- Added wrappers for all current functions so that they can be called with gpioAddresses 
- Added compound literal gpioAddresses for adc internal channels (REF, TEMP, BAT)
- Added new Gpio AdcPinCallback typedef to allow funcs with gpios as params to be registered with register_callback_pin func
Adc.c
- Added new static AdcPinInterrupt array to keep track of registered callbacks and readings, ensured that although registered callbacks may exist in either AdcPinInterrupt or AdcInterrupt array, only one can be registered per channel
- Adjusted logic of ADC1_COMP_IRQHandler() to check which type of callback is registered, so that it can call with the right params
- Added x86 functionality
Test_adc.c
- Added tests for new functions using same logic as those used for adcchannel functions

2020-09-19 03:06 UTC, copperium requested changes
I'm not sure if we should be adding this much complexity to the module to maintain two options for the callback function, one taking a GpioAddress and one taking an AdcChannel. The callback feature isn't used at all outside test_adc.c in this codebase, and in the MSXII codebase it was only used in a demo "adc_driver" project. We could just say that to use the callback feature you'll have to use the legacy AdcChannel. Thoughts @g-jessmuir?

I also think it's worth supporting the legacy AdcChannel functions at least for `ADC_CHANNEL_TEMP/REF/BAT`, since I really don't like the compound literal GpioAddress hack to shoehorn ADC channel values into a GpioAddress - it's confusing and bug-prone.

Overall, great job Mitchell! I can tell you put a lot of work into improving adc.

2020-09-19 03:06 UTC, copperium commented on libraries/ms-common/test/test_adc.c
> +}
This test won't be necessary if/when you remove `ADC_CHANNEL_TEMP_PIN` etc

2020-09-22 03:08 UTC, copperium requested changes
Just a couple nitpicks and things I missed last time, should be ready to merge after these updates

2020-09-22 03:08 UTC, copperium commented on libraries/ms-common/test/test_adc.c
> -void test_adc_mock_reading() {
Why did you remove this test?

2020-09-23 01:11 UTC, mitchellostler commented on libraries/ms-common/test/test_adc.c
> +  s_callback_ran = false;
It is incremented in prv_rx_callback which is called by other tests as well. This means that I need to reset it before i run my test no?

2020-09-23 01:26 UTC, mitchellostler commented on libraries/ms-common/src/stm32f0xx/adc.c
> +  s_adc_interrupts[adc_channel].pin_callback = callback;
added prv_reset_channel() which sets all params of adcInterrupt struct to zero

2020-09-23 01:56 UTC, mitchellostler commented on libraries/ms-common/src/stm32f0xx/adc.c
> +  s_adc_interrupts[adc_channel].pin_callback = callback;
Also created prv_check_channel() function to replace same logic used in almost all the adcChannel funcs, and to allow gpio_pin_register_callback to run this check as well without adding redundant code

2020-09-24 01:59 UTC, copperium approved these changes

2020-09-24 02:07 UTC, merged