SOFT 170 can_handler for bms carrier
uw-midsun/firmware_xiv pull request #169
Opened 2020-09-21 21:34 UTC by shahhet14

Created can_handler module to tx current, voltage, temperature, relay states and fan states.

2020-09-22 04:49 UTC, g-jessmuir requested changes
just a few small changes then we should be good, thanks! also move your codegen tooling PR out of draft if you're good to merge

2020-09-22 04:49 UTC, g-jessmuir commented on projects/bms_carrier/src/can_handler.c
> +  prv_periodic_tx(SOFT_TIMER_INVALID_TIMER, storage);
I think it makes sense to actually start a soft timer here for 1 second to give other things a chance to collect readings before TXing them. You can either set the 1 second to a #define or just add a comment explaining it's a one-off delay to let data accumulate

2020-09-23 02:21 UTC, shahhet14 commented on libraries/codegen-tooling/inc/can_pack.h
> +#define CAN_PACK_SOLAR_DATA(msg_ptr, data_point_type_u32, data_value_u32)                 \
Not intentional, the only changes should've been the changes to the fan state message. Might be an outdated branch or something.

2020-09-26 12:39 UTC, shahhet14 commented
Made the changes you requested. For the wait between messages, I've made it 85 ms for now.

2020-09-26 19:12 UTC, g-jessmuir approved these changes

2020-09-26 19:12 UTC, merged