fw102 hw
uw-midsun/firmware_xiv pull request #179
Opened 2020-10-04 03:10 UTC by nadia-nguyen

2020-10-04 21:43 UTC, g-jessmuir requested changes
Looks correct, just a few things:
- please don't include the files for the hello_world test project; you can avoid this by not 'git add'ing them before commiting, or just deleting them and commiting again
- just nitpicks for the actual assignment
Aside from that looks good 🙂

2020-10-04 21:43 UTC, g-jessmuir commented on projects/timer_challenge/src/main.c
> +#include "delay.h"       // for delays
Doesn't seem like you use this include, please remove

2020-10-04 21:43 UTC, g-jessmuir commented on projects/timer_challenge/src/main.c
> +  soft_timer_start_millis(500, prv_timer_callback, storage, NULL);  // restart timer
Please use a #define for 500, e.g. `#define TIMER_PERIOD_MS 500` at the top after the #includes

2020-10-04 21:43 UTC, g-jessmuir commented on projects/timer_challenge/src/main.c
> +  soft_timer_start_millis(500, prv_timer_callback, &storage, NULL);
same comment here as above about #define 500

2020-10-18 02:08 UTC, copperium commented
Looks good, please move on to FW 103. Closing since homework is complete.

2020-10-18 02:08 UTC, closed without merging