Soft 333 add mpxe pca9539r
uw-midsun/firmware_xiv pull request #225
Opened 2020-11-07 16:26 UTC by JarvisWeng

2020-11-14 16:41 UTC, g-jessmuir requested changes
I think we need to change it a bit since sending 4kb seems a bit much every message

2020-11-15 21:51 UTC, JarvisWeng commented on mpxe/protos/stores.proto
> -  ADS1259 = 3;
oh, i thought i didn't. My bad.

2020-11-15 21:56 UTC, JarvisWeng commented on libraries/ms-drivers/src/x86/pca9539r_gpio_expander.c
> +  prv_init_store();
sure

2020-11-15 21:57 UTC, JarvisWeng commented on libraries/ms-drivers/src/x86/pca9539r_gpio_expander.c
> +       s_pin_settings[i2c_port][gpio_pin].state = msg->state[i];
i have no idea what happened to formatting everywhere

2020-11-15 21:58 UTC, JarvisWeng commented on libraries/ms-drivers/src/x86/pca9539r_gpio_expander.c
> +  s_store.n_state = MAX_I2C_ADDRESSES * NUM_PCA9539R_GPIO_PINS;
sure

2020-11-15 22:22 UTC, JarvisWeng commented on mpxe/sims/pca9539r.py
> +            assert(self.state[x]  == state)
Actually this is in the `sim` module, so how would I access the `TestPca9539r`? I only pass in the `proj`, not sure how to go up a layer to get the test

2020-11-15 22:24 UTC, g-jessmuir commented on mpxe/sims/pca9539r.py
> +            assert(self.state[x]  == state)
oh wait you’re right, sorry why do we need the assert at all then?

2020-11-15 22:25 UTC, JarvisWeng commented on mpxe/sims/pca9539r.py
> +            assert(self.state[x]  == state)
nvm, i figured it out. I thought I had inherit this function.

2020-11-15 22:56 UTC, JarvisWeng commented on mpxe/sims/pca9539r.py
> +            assert(self.state[x]  == state)
Oh, I just assert to make sure the values are being passed to the store correctly. It's ok, it's my function so I passed in the test instead.

2020-11-21 16:40 UTC, g-jessmuir approved these changes

2020-11-21 16:40 UTC, merged