[Soft-332] mpxe mcp23008 support
uw-midsun/firmware_xiv pull request #241
Opened 2020-12-03 03:20 UTC by mitchellostler

Added mcp23008 driver to mpxe

2020-12-03 03:24 UTC, mitchellostler commented on mpxe/sims/mcp23008.py
> +    def update_pin_state(self, proj, pin, state):
This isn't used in the smoketest, but I figured it will be needed if we ever to simulate any inputs from an mcp23008

2020-12-07 16:49 UTC, g-jessmuir requested changes
just some weird formatting stuff (rip no travis) otherwise I think it looks good! can't hurt to manually run pylint / lint though

2020-12-07 16:49 UTC, g-jessmuir commented on mpxe/sims/mcp23008.py
> +            mcp         = stores[MCP23008_KEY]
equals signs aren't lined up here :(

2020-12-10 00:33 UTC, g-jessmuir approved these changes

2020-12-10 00:33 UTC, merged