Added autopep8 format to build process
uw-midsun/firmware_xiv pull request #276
Opened 2021-02-08 04:05 UTC by hzhou0

Autopep8 needs to be installed through apt.

2021-02-11 03:33 UTC, copperium requested changes
Great job Henry! To stop Travis from failing you'll want to run your `make format` over the repo - this will make your PR huge but that's alright.

2021-02-14 02:45 UTC, copperium requested changes
I'm not sure what version of `make format` you formatted with, but it seems to have caused a *whole lot* of changes to headers and some changes that the current `make format` actually corrects, e.g. solar_config.c. (I'm pretty sure that autopep8 isn't supported to touch C files...) Could you use git to reset all files other than the Makefile, then (after adding `unity` as ignored) `make format` again? That way the whole repo is formatted like the current `make format` wants.

2021-02-14 02:45 UTC, copperium commented on Makefile
> +AUTOPEP8_CONFIG:= -a --max-line-length 100 -r
Could you also add the whole `unity` directory as ignored? It contains a bunch of python files which aren't *really* owned by us (they're part of the unity test library) and formatting them would probably cause merge conflicts.

(Also, please put a space before the `:=`)

2021-02-14 06:02 UTC, hzhou0 commented
I checked the Makefile history and can confirm I have not made any changes to the original c formatting code. It still seems to be formatting c files.

2021-02-16 01:15 UTC, copperium commented
Are you doing `make format` inside the vagrant box? I wonder if you have a different version of clang-format on your machine.

2021-02-16 01:56 UTC, copperium commented
You also need to add a `pip install --user autopep8` to the travis script in .travis.yml (by the pip install --user pylint) so that travis doesn't error because it can't find autopep8.

2021-02-17 03:53 UTC, copperium approved these changes

2021-02-17 04:00 UTC, merged