[Soft 483] Regen braking toggling
uw-midsun/firmware_xiv pull request #390
Opened 2021-06-03 05:34 UTC by danielzyy

2021-06-09 22:50 UTC, ryandancy requested changes
Awesome job Daniel, I love the test cases! Sorry for taking so long to review - it looks great, just one thing to add that shouldn't take too long.

2021-06-09 22:50 UTC, ryandancy commented on projects/centre_console/src/regen_braking_toggle.c
> +  regen_braking_state = false;
IMO, just to enforce that this is the default state on power-up across the system, I think that we should try and send the set-regen-braking CAN message on init (i.e. call `prv_process_request(false)` here as well). That way everything is consistent even if one component in the system has a different default.

2021-06-09 22:50 UTC, ryandancy commented on projects/centre_console/inc/regen_braking_toggle.h
> +bool get_regen_braking_state();
Nitpicks: the parameter lists here should be `(void)` rather than `()`, same in the .c file too.

2021-06-09 22:50 UTC, ryandancy commented on projects/centre_console/src/regen_braking_toggle.c
> +  if (e != NULL && e->id == POWER_MAIN_SEQUENCE_EVENT_COMPLETE) {
Maybe document this behaviour (that we set the regen braking state to true upon power main sequence complete) in the header file somewhere

2021-06-24 00:23 UTC, ryandancy approved these changes

2021-06-24 00:55 UTC, ryandancy commented
Ah looks like CI caught some format stuff, could you address?

2021-06-30 22:36 UTC, ryandancy commented
Fixed a few merge conflicts that cropped up, also had to get rid of the `TELEMETRY` target on the regen braking CAN message because build_dbc.py was trying to generate an ACK message from telemetry in the DBC file. @AveryChiu64 should removing the `TELEMETRY` target cause any issues? (or is putting `TELEMETRY` as a target just documentation?)

2021-06-30 23:02 UTC, merged

2021-07-01 00:12 UTC, AveryChiu64 commented
Removing the TELEMETRY target is fine. Telemetry will pick up all CAN messages regardless of the target