Soft 560 jump to app client script
uw-midsun/firmware_xiv pull request #473
Opened 2021-11-10 01:42 UTC by BENJIGAO

Main concern is whether the script handles response datagrams correctly. A DatagramListener is initialized and connected to CAN, but during testing, only the jump to application datagram is handled by the callback (no instances of response datagrams) as far as I can tell.

2021-11-13 17:10 UTC, ryandancy requested changes
Awesome Ben! Sorry for the delayed review, the core of it looks good.

2021-11-13 17:10 UTC, ryandancy commented on projects/bootloader/scripts/test_jump_application.py
> +            listener_message = listener.get_message()
The purpose of the unit test is to test that the code you wrote works (i.e. the `jump_to_application` function). To do this, you'll need to call your function. Specifically, what I'd recommend is setting up your sender, listener, and notifier as you've done, then calling `jump_to_application` with the test nodes and listener. Then in the callback, you should assert that the datagram type is `TEST_DATAGRAM_TYPE_ID` and respond with the appropriate response datagrams, to simulate controller boards responding to the datagram.

Finally, once `jump_to_application` returns, you should verify that it returned the correct value. You should also check that the `callback` was called! (You can do this by setting a variable from `callback` and checking it in the test function - could be easiest to define `callback` inside the test function.)

2021-11-13 17:29 UTC, ryandancy commented on projects/bootloader/scripts/jump_application.py
> +        listener_message = listener.get_message()
For getting the `board_id` into the callback, also take a look at Bafran's PR, looks like he's already implemented it. Might be worth merging his branch into yours for those changes.

2021-11-13 17:33 UTC, ryandancy commented on projects/bootloader/scripts/test_jump_application.py
> +            listener_message = listener.get_message()
Also look at Bafran's PR for sending a datagram from an arbitrary board ID, he's got that implemented too (with the `sender_id` parameter of `Datagram.send`).

2021-11-13 17:59 UTC, ryandancy commented on projects/bootloader/scripts/jump_application.py
> +    can.Notifier(sender.bus, [listener])
One other thing: you'll probably want to assign this to a variable to make sure it doesn't get garbage-collected.

2021-11-20 19:11 UTC, BENJIGAO commented
I made changes based on comments for both my function and test file. Let me know if there's anything I should change!

2021-12-04 18:37 UTC, ryandancy requested changes
Sorry for the super delayed feedback, just a few more comments!

2021-12-04 18:37 UTC, ryandancy commented on projects/bootloader/scripts/test_jump_application.py
> +        self.assertEqual(self.callback_triggered, True)
This assertion is failing on my machine. Is it working on yours? If so, let's have a call to see why it's inconsistent; if not, run this test with `make pytest PLATFORM=x86 PROJECT=bootloader TEST=jump_application` and debug why.

2021-12-30 18:25 UTC, ryandancy approved these changes

2021-12-30 18:26 UTC, merged