Completed fw 103 homework
uw-midsun/firmware_xiv pull request #489
Opened 2022-01-23 20:28 UTC by ShahriarAhnaf

please review for accuracy.

2022-01-26 17:26 UTC, ShiCheng-Lu reviewed
There are 2 errors that would stop this project from doing what is intended, but apart from that, there are only minor problems. 

you should run formatting and linting before you push. If you've set up the github hooks, it should format and lint before every commit.

your branch name should be `soft_999_...` with a underscore.

you can move on to 104 after fixing the errors, and probably take on a ticket if you are interested.

2022-01-26 17:26 UTC, ShiCheng-Lu commented on projects/soft999_ahnaf_shahriar_fw_103/src/main.c
> +
gpio_it_init() needs to be called to enable interrupts from gpio pins

2022-01-26 17:26 UTC, ShiCheng-Lu commented on projects/soft999_ahnaf_shahriar_fw_103/src/main.c
> +  delay_ms(200);
what is this delay for?

2022-01-26 17:26 UTC, ShiCheng-Lu commented on projects/soft999_ahnaf_shahriar_fw_103/src/main.c
> +  gpio_init_pin(&potentiometer_addr, &pot_settings);
you also need to init the button pin to use it

2022-01-26 17:26 UTC, ShiCheng-Lu commented on projects/soft999_ahnaf_shahriar_fw_103/src/main.c
> +static void button_interrupt_handler(const GpioAddress *addy, void *context) {
we prefix static methods with `prv_` and global static variables with `s_`.

(addy is an interesting variable name, typo?)

2022-01-26 17:26 UTC, ShiCheng-Lu commented on projects/soft999_ahnaf_shahriar_fw_103/src/main.c
> +    );
here you are not using the `void * context` in your function anyway so its ok to pass in `NULL`. 

format is also complaining about this ending parenthesis, I would put it straight after the last argument.

2022-01-26 17:26 UTC, ShiCheng-Lu commented on projects/soft999_ahnaf_shahriar_fw_103/src/main.c
> +    // let cpu run wild until interrupt.
you can add a `wait()` from `wait.h` here to save on processing time.

2022-01-26 17:26 UTC, ShiCheng-Lu commented on projects/soft999_ahnaf_shahriar_fw_103/src/main.c
> +  soft_timer_init();
I don't think soft timer is used in this project, you don't need to include and init it.

2022-02-05 18:22 UTC, mitchellostler requested changes
Take a look at and address Shicheng's requested changes when you get the chance then we can move you on to a task

2025-07-06 19:57 UTC, closed without merging